Support update SQL & fix precision problem
cmu-db/peloton-test pull request #52
Opened 2017-07-10 20:29 UTC by lixupeng

I do two minor changes:

1) use statementUpdate() to run those CREATE, DROP, INSERT.... statements in trace files. 

2) use BigDecimal to solve the double error #50

2017-07-11 02:44 UTC, tli2 requested changes

2017-07-11 02:44 UTC, tli2 commented on src/main/java/edu/cmu/cs/db/peloton/test/common/TestContainer.java
> -            row.add(resultSet.getObject(i));
This probably won't work as BigDecimal::valueOf uses the string representation of a double as the canonical value and that might already have round-off errors. You should use a delta comparison instead.

2017-07-11 19:28 UTC, apavlo commented
@lixupeng I would not check in the SQLite traces into the repository. They are going to be huge. You can download them from the peloton website.

The setup script should also probably be in the regular peloton repository.

2017-07-12 19:51 UTC, apavlo commented
@lixupeng You need to expunge the sqlite trace file completely from your PR. Otherwise it bloats the size of the repo because it's still in the history:

https://help.github.com/articles/removing-sensitive-data-from-a-repository/

2017-07-12 23:30 UTC, lixupeng commented
@apavlo ok, I've fixed it.

2017-07-21 01:40 UTC, merged